# Generated by Django 4.0.3 on 2022-04-20 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomEntreprise', models.CharField(blank=True, default='Entreprise', max_length=50, null=True)),
                ('anneeCreation', models.IntegerField(blank=True, default=2000, null=True)),
                ('activite', models.CharField(blank=True, default='Activité', max_length=100, null=True)),
                ('effectif', models.IntegerField(blank=True, default=1, null=True)),
                ('capital', models.IntegerField(blank=True, default=10000, null=True)),
                ('nomDirecteur', models.CharField(blank=True, default='Directeur', max_length=50, null=True)),
                ('numeroContribuable', models.IntegerField(blank=True, default=1, null=True)),
                ('formeJuridique', models.CharField(blank=True, choices=[('SCS', 'SCS'), ('SNC', 'SNC'), ('SARL', 'SARL'), ('SA', 'SA'), ('SAS', 'SAS'), ('GIE', 'GIE'), ('SEP', 'SEP'), ('SCP', 'SCP'), ('SCI', 'SCI'), ('SP', 'SP')], default='SP', max_length=50, null=True)),
                ('chiffreAffaire', models.IntegerField(blank=True, default=10000, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Entreprise', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
