# Generated by Django 4.0.3 on 2022-04-20 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entreprise', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entreprise',
            old_name='user',
            new_name='identifiant',
        ),
    ]
