# Generated by Django 4.0.3 on 2022-04-21 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Entreprise', '0002_rename_user_entreprise_identifiant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='effectif',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='formeJuridique',
            field=models.CharField(blank=True, choices=[('SCS', 'SCS'), ('SNC', 'SNC'), ('SARL', 'SARL'), ('SA', 'SA'), ('SAS', 'SAS'), ('GIE', 'GIE'), ('SEP', 'SEP'), ('SCP', 'SCP'), ('SCI', 'SCI'), ('SP', 'SP')], default='SARL', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='identifiant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entreprise', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='numeroContribuable',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
    ]
