# Generated by Django 4.0.3 on 2022-04-23 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employe', '0003_remove_employe_identreprise_employe_identifiantuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='identifiantUser',
        ),
    ]
