# Generated by Django 4.0.3 on 2022-04-23 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Employe', '0004_remove_employe_identifiantuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='identifiantUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employé', to=settings.AUTH_USER_MODEL),
        ),
    ]
