# Generated by Django 4.0 on 2022-05-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Indemnites', '0001_initial'),
        ('Prime', '0001_initial'),
        ('Employe', '0005_employe_identifiantuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='indemnite',
            field=models.ManyToManyField(to='Indemnites.Indemnites'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='prime',
            field=models.ManyToManyField(to='Prime.Prime'),
        ),
    ]
