# Generated by Django 4.0 on 2022-05-27 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Entreprise', '0003_alter_entreprise_effectif_and_more'),
        ('Employe', '0006_alter_employe_indemnite_alter_employe_prime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='indemnite',
        ),
        migrations.AddField(
            model_name='employe',
            name='idEntreprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employé', to='Entreprise.entreprise'),
        ),
    ]
