# Generated by Django 4.0 on 2022-05-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adresse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adresse',
            name='entreprise',
        ),
        migrations.AddField(
            model_name='adresse',
            name='valeur',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='typeAdresse',
            field=models.CharField(choices=[('Adresse mail', 'Adresse mail'), ('Téléphone', 'Téléphone'), ('Site Internet', 'Site Internet'), ('Boite postale', 'Boite postale'), ('Pays', 'Pays'), ('Ville', 'Ville'), ('Quartier', 'Quartier'), ('Inplantation', 'Inplantation'), ('Fax', 'Fax')], max_length=50, null=True),
        ),
    ]
